server:
  port: 9903
spring:
  application:
    name: find-person-with-car-service
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    username: moein
    password: myjava123
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9001/eureka}